n_trials: 100
timeout: null

n_jobs: 1

sampler:
  type: "TPESampler"
  seed: 42
  n_startup_trials: 10
  multivariate: false

pruner:
  type: "MedianPruner"
  n_startup_trials: 5
  n_warmup_steps: 2
  interval_steps: 1

direction: "maximize"
metric: "recall"

show_progress_bar: true

study:
  name_prefix: "pneumothorax_opt"
    
  save_study: True
  storage: null  # "sqlite:///optuna.db"

